apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "boot"
  namespace: "boot-staging"
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - boot.staging.revaturelabs.com
    secretName: boot-staging-tls
  rules:
  - host: boot.staging.revaturelabs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: boot
          servicePort: 80
