apiVersion: v1
kind: Service
metadata:
  name: boot-svc
  labels:
    batch: 1603_mar18_java
    trainer: taylor_kemper 
    app: boot
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    batch: 1603_mar18_java
    trainer: taylor_kemper 
    app: boot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boot-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        batch: 1603_mar18_java
        trainer: taylor_kemper 
        app: boot
    spec:
      containers:
      - name: boot
        image: tjkemper/boot:latest
        ports:
        - containerPort: 8080
#        resources:
#          limits:
#            cpu: 100m
#            memory: 200Mi
#          requests:
#            cpu: 200m
#            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: boot-hpa
spec:
  scaleRef:
    kind: Deployment
    name: boot-deployment
    subresource: scale
  minReplicas: 3
  maxReplicas: 12
  cpuUtilization:
    targetPercentage: 50
