  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:  
    name: "boot"
    labels: 
      app: "boot"
#      environment: "dev"
  spec: 
    replicas: 3
    template: 
      metadata: 
        name: "boot"
        labels: 
          app: "boot"
#          environment: "dev"
      spec: 
        containers: 
          - name: "boot"
            image: "tjkemper/boot-app:0.2"
            ports: 
              - containerPort: 8080
            resources:
              requests:
                cpu: 0.1
                memory: 400M
              limits:
                cpu: 0.1
                memory: 400M
           #livenessProbe:
            #  httpGet:
            #    path: /
            #    port: 8080
            #  initialDelaySeconds: 60
            #  timeoutSeconds: 5
