  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:  
    name: "boot"
    labels: 
      app: "boot"
      track: "stable"
  spec: 
    replicas: 3
    template: 
      metadata: 
        name: "boot"
        labels: 
          app: "boot"
          track: "stable"
      spec: 
        containers: 
          - name: "boot"
            image: "tjkemper/boot-app:0.2"
            ports: 
              - containerPort: 8080
            resources:
              requests:
                cpu: 0.1
                memory: 400M
              limits:
                cpu: 0.1
                memory: 400M
#            livenessProbe:
#              httpGet:
#                path: /healthz
#                port: 8080
#              initialDelaySeconds: 20
#              timeoutSeconds: 5
#            readinessProbe:
#              httpGet:
#                path: /readiness
#                port: 8080
#              initialDelaySeconds: 40
#              timeoutSeconds: 5
